---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    fluxcd.io/automated: "true"
  name: contoso
  namespace: default
  labels:
    app: contoso
spec:
  selector:
    matchLabels:
      app: contoso
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: contoso
    spec:
      containers:
      - name: contoso
        image: navjots35/dotnet:795239407
        ports:
        - containerPort: 80
